# Generated by Django 2.2.13 on 2020-10-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoSubastado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.FloatField()),
                ('condiciones', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Chocado', 'Chocado'), ('Optimo', 'Optimo')], default='Optimo', max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoSubastado', to='api.Auto')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoSubastado', to='api.Profile')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoSubastado', to='api.Subasta')),
            ],
        ),
    ]
