# Generated by Django 2.2.13 on 2020-10-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_autosubastado_subasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAutoSubastado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='autoSubastado')),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('autoSubastado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.AutoSubastado')),
            ],
        ),
    ]
