# Generated by Django 2.2.13 on 2020-10-30 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fotoautosubastado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosubastado',
            name='provedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoSubastado', to='api.Proveedor'),
        ),
    ]
