# Generated by Django 2.2.13 on 2020-10-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201030_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
